<?php

/**
 * Implements hook_theme().
 */
function learning_theme() {

    return [
        'learning_news_block' => [
            'variables' => [
                'data' => NULL
            ],
            'template' => 'news-results'
        ],
        'news_page' => [
            'variables' => [
                'data' => NULL
            ],
            'template' => 'news-page'
        ],
    ];
}